### ISSUE TITLE
Reverse geocoding

### ISSUE THREAD

**Issue by antonsivogrivov** [DenisCarriere/geocoder-geojson#1]
Hi!

What about reverse geocoding?

**Comment by DenisCarriere** [comment]
You have to star the project before doing any request :)

**Comment by antonsivogrivov** [comment]
Done :)

**Comment by DenisCarriere** [comment]
:+1: Awesome! I just started this project, I'm slowly going to port over my previous Python geocoder library to Javascript.
https://github.com/DenisCarriere/geocoder

Almost got the reverse geocoding done, will be available soon

**Comment by antonsivogrivov** [comment]
I look forward :)

**Comment by DenisCarriere** [comment]
@tonygriv Ok it's up on NPM, have a try at it and if something doesn't work, just re-open the issue with an explaination.
