### ISSUE TITLE
Locale ignored for google

### ISSUE THREAD

**Issue by terry90** [DenisCarriere/geocoder-geojson#10]
The response of this is in french (I am french, and so my browser settings)
``` js
  geocoder.google(address, { language: 'en' })
    .then(geojson => cb({ ...geojson, provider: 'google' }))
    .catch((err) => {
      console.warn(err);
    });
```

**Comment by DenisCarriere** [comment]
@terry90 Thanks for pointing that out, I just fixed it and published a new release.

Added these to the test cases.

https://github.com/DenisCarriere/geocoder-geojson/blob/master/test.ts#L10-L17

Next time provide the specific address you are referencing to.

**Comment by terry90** [comment]
Yeah sorry, but it was not one address, that's why I did not precised one. 😄 
Thanks for fixing this issue !

**Comment by DenisCarriere** [comment]
@terry90 No worries, it was clearly a bug :+1: Thanks for reporting it
