### ISSUE TITLE
Doesn't work in IE11

### ISSUE THREAD

**Issue by polikin** [DenisCarriere/geocoder-geojson#3]
The only error IE11 return is `Expected ')'`.

When I compile my js (with browserify) I get this error:

`uglify-js failed on node_modules/geocoder-geojson/index.js : SyntaxError: Unexpected token operator «=», expected punc «,» (line: 37, col: 33, pos: 2041)`

**Comment by DenisCarriere** [comment]
@polikin This is an ES6 module, you might need to use something like Babel. It uses Async & Await functionality from ES6.

This library was intended to be used with NodeJS, however I'm supportive of supporting IE 11 if there's an easy solution to support the many web browsers out there.

**Comment by DenisCarriere** [comment]
@polikin Try using `Webpack`, they just released a major release and seems to be very straight forward to use.

Unfortunately, I personally haven't gotten it to work with `geocoder-geojson`, but maybe it's my current setup, I have to experiment more with it.

https://webpack.js.org/

**Comment by DenisCarriere** [comment]
Oh it's breaking because of default values in the functions.

```javascript
function mapbox(address, options = providers_1.Mapbox.Options) {
```

Try using Webpack instead of Browserify

**Comment by DenisCarriere** [comment]
@polikin I've got it working now with Browserify & Webpack, so both of them are good to go, I've included some examples in this repo.

https://github.com/DenisCarriere/geocoder-geojson/tree/master/examples

**Comment by polikin** [comment]
Cool! Thanks!
