### ISSUE TITLE
Remove color.js dependency

### ISSUE THREAD

**Issue by terry90** [DenisCarriere/geocoder-geojson#5]
color.js dependency generates this waring due to a dynamic require:

```
WARNING in ./~/colors/lib/extendStringPrototype.js
Critical dependencies:
101:31-45 the request of a dependency is an expression
 @ ./~/colors/lib/extendStringPrototype.js 101:31-45
```

This lib is kinda deprecated, since it is used only once in this project, either remove it or replace it with something like https://github.com/chalk/chalk

**Comment by DenisCarriere** [comment]
👍 I'm going to remove it, good call. In the future I will try to use the `Fetch` API and remove `axios` entirely, however last time I did that nothing worked anymore 😢
