### ISSUE TITLE
Cannot set default Authorization header in my App without messing geocoder's axios

### ISSUE THREAD

**Issue by terry90** [DenisCarriere/geocoder-geojson#9]
When setting:
`axios.defaults.headers['Authorization']`
in my app,

Google maps api will refuse the preflight request:
`Request header field Authorization is not allowed by Access-Control-Allow-Headers in preflight response.`

I changed my code to set the header in the post/get method and not in defaults.

I think it should be wise to create an instance of axios with no headers to reset the global config with the geocoder.
like `instance = axios.create(); instance.defaults.headers = {}; instance.get....`

**Comment by DenisCarriere** [comment]
@terry90 Test this against the latest `npm` version, it should be fixed now.

Close the issue after or post what is happening.

**Comment by terry90** [comment]
You are incredibly reactive !
Thank you, I will close if fixed 👍

**Comment by terry90** [comment]
Woops, seems like `headers.common` is not set.
`Cannot read property 'Authorization' of undefined`

**Comment by DenisCarriere** [comment]
@terry90 last commit should fix that `undefined` issue.

**Comment by terry90** [comment]
Works like a charm
